---
- name: Run updates
  ansible.builtin.apt:
    name: '*'
    state: latest
    update_cache: yes
  register: update_result

- name: Reboot after updates
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: update_result.changed