---
- name: Install Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: latest

- name: Configure Fail2Ban from template
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  no_log: true
  notify:
    - Restart Fail2Ban