---
- name: Configure new server
  hosts: all
  become: yes
  vars:
    dev_port: 8081
    prod_port: 8080
    dev_image: ghcr.io/eoinhealy0/my-site:dev
    prod_image: ghcr.io/eoinhealy0/my-site:prod
  roles:
    - security_updates
    - configure_docker
    - configure_fail2ban
    - configure_nginx
    - deploy_site
    - configure_cloudflare