---
- name: Configure new server
  hosts: all
  become: yes
  vars:
    green_port: 8081
    blue_port: 8080
    active_color: blue
  roles:
    - security_updates
    - install_docker
    - install_fail2ban
    - install_nginx